myPaths <- .libPaths()
myPaths <- c("/app/r-lib-local", myPaths)
.libPaths(myPaths)
local({r <- getOption("repos")
       r["CRAN"] <- "http://archive.linux.duke.edu/cran/" 
       options(repos=r)
})
install.packages("SqlRender")
install.packages("callr")
install.packages("devtools")
install.packages("drat")
install.packages("rJava")
library(devtools)
drat::addRepo("OHDSI")
devtools::install_github("OHDSI/DataQualityDashboard")
devtools::install_github("OHDSI/Tantalus")
